version: "3"

services:

  selenium-hub:
    image: selenium/hub:latest
    environment:
      - GRID_MAX_SESSION=10
      - GRID_BROWSER_TIMEOUT=100000
      - GRID_TIMEOUT=90000
      - GRID_NEW_SESSION_WAIT_TIMEOUT=300000
    container_name: selenium-hub
    ports:
      - "4444:4444"

  chrome:
    image: selenium/node-chrome:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=10
      - NODE_MAX_INSTANCES=10

  firefox:
    image: selenium/node-firefox:latest
    depends_on:
      - selenium-hub
    environment:
      - HUB_HOST=selenium-hub
      - HUB_PORT=4444
      - NODE_MAX_SESSION=10
      - NODE_MAX_INSTANCES=10
